### ISSUE TITLE
D3-rshiny-vis: Repository structure

### ISSUE THREAD

**Issue by bastianilso** [med-material/d3-rshiny-vis#7]
It would be great with a repository structure where:

1) each folder represent a visualization project
2) where you guys can work in branches on each your visualization projects.
3) where you can make pull requests to master once your work is "stable" and ready for a code review.

I'm assigning @aldsanms to lead this effort.

**Comment by aldsanms** [comment]
I reworked the git structure and published my projects on git.

![feefef](https://user-images.githubusercontent.com/73821252/200594253-d16376f4-f231-4274-ad5c-0329d91fbcdf.PNG)
